function Rowdata() {
  const row = [
    {
      SlNo: "1",
      Description:
        "Cutting open BT road surface including water bound macadam including labour charges all leads , lifts and conveyance of all materials etc complete as directed by the departmental officers for pipeline trenches.",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COBT_desc"
    },
    {
      SlNo: "",
      Description: "for 300mm dia pipe line trenches",
      item: "1",
      Nos: "2",
      L: "0",
      B: "0",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Sqm",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COBT__data_300pl"
    },
    {
      SlNo: "",
      Description: "for 250mm dia pipe line trenches",
      item: "1",
      Nos: "2",
      L: "0",
      B: "0",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Sqm",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COBT__data_250pl"
    },
    {
      SlNo: "",
      Description: "for 200mm dia pipe line trenches",
      item: "1",
      Nos: "2",
      L: "0",
      B: "0",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Sqm",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COBT__data_200pl"
    },
    {
      SlNo: "",
      Description: "for 150mm dia pipe line trenches",
      item: "1",
      Nos: "2",
      L: "0",
      B: "0",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Sqm",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COBT__data_150pl"
    },
    {
      SlNo: "",
      Description: "for 100mm dia pipe line trenches",
      item: "1",
      Nos: "2",
      L: "0",
      B: "0",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Sqm",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COBT__data_100pl"
    },
    {
      SlNo: "",
      Description: "for Junction portions",
      item: "1",
      Nos: "3",
      L: "0",
      B: "0",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Sqm",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COBT__data_jp"
      
    },
    {
      SlNo: "",
      Description: "for Sluice Valve trenches",
      item: "1",
      Nos: "6",
      L: "0",
      B: "0",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Sqm",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COBT__data_svt"
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "Sqm",
      Rate: "1342.00",
      unit: "10Sqm",
      Amount: "0.00",
      row_identity: "COBT__amt"
    },
    /// CC starts here
    {
      SlNo: "2",
      Description:
        "Cutting open CC road surface including labour charges, all leads and other incidental and operational charges , tools and plants etc complete for pipeline trenches.",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COCC_desc"
    },
    {
      SlNo: "",
      Description: "for 300mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COCC__data_300pl"
    },
    {
      SlNo: "",
      Description: "for 250mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COCC__data_250pl"
    },
    {
      SlNo: "",
      Description: "for 200mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COCC__data_200pl"
    },
    {
      SlNo: "",
      Description: "for 150mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COCC__data_150pl"
    },
    {
      SlNo: "",
      Description: "for 100mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COCC__data_100pl"
    },
    {
      SlNo: "",
      Description: "for Junction portion ",
      item: "1",
      Nos: "3",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COCC__data_jp"
    },
    {
      SlNo: "",
      Description: "for sluice valve trenches",
      item: "1",
      Nos: "3",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0.00",
      Qty_unit: "Sqm",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "COCC__data_svt"
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "2793.00",
      unit: "Cum",
      Amount: "0.00",
      row_identity: "COCC_amt"
    },
    {
      SlNo: "3",
      Description:
        "Earth work excavation in all available soils such as red earth, hard gravelly soils but excluding soft and hard disintegrated rock, depositing on bank with an initial lead of 10m. and lift of 2m etc complete.",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "EWEX_desc"
    },
    {
      SlNo: "",
      Description: "for 300mm dia Pipeline trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: "",
      row_identity: "EWEX_data_300pl"
    },
    {
      SlNo: "",
      Description: "for 250mm dia Pipeline trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 200mm dia Pipeline trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 150mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 100mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for Junction portion ",
      item: "1",
      Nos: "6",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for sluice valve trenches",
      item: "1",
      Nos: "6",
      L: "0",
      B: "0",
      D: "0",
      Qty: "0",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "343.00",
      unit: "Cum",
      Amount: "0.00"
    },
    {
      SlNo: "4",
      Description:
        "Cutting of sheet rock for laying of pipe line trench including cost and conveyance of all materials, labour charges etc complete",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "15% of total earth work qty",
      item: "1",
      Nos: "1",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "3124.00",
      unit: "Cum",
      Amount: "0.00"
    },
    {
      SlNo: "5",
      Description:
        "Cutting of C.I./ AC pipe without water in the main  by hammering chesiling etc. complete. ",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "300 mm dia DI main",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "418.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "250 mm dia DI main",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "348.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "200 mm dia DI main",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "278.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "150 mm dia DI main",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "209.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "100 mm dia DI main",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "111.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "6",
      Description:
        "Lowering laying and jointing of DI pipes in to the ready made trenches to the true alightment and gradiant including all sundries excluding cost of conveyence of pipes and materials etc, complete                ",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 300mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt ",
      Rate: "202.00",
      unit: "Rmt",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 250mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt ",
      Rate: "157.00",
      unit: "Rmt",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 200mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt ",
      Rate: "116.00",
      unit: "Rmt",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 150mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt ",
      Rate: "80.00",
      unit: "Rmt",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 100mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt ",
      Rate: "49.00",
      unit: "Rmt",
      Amount: "0.00"
    },
    {
      SlNo: "7",
      Description:
        "Jointing of of DI pipes with S/S ends in ready made trenches true alightment with Rubber Gaskets excluding cost of materials and including all labour charges etc,complete.",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: " for 300 mm dia",
      item: "1",
      Nos: "1",
      L: "0",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "235.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: " for 250 mm dia",
      item: "1",
      Nos: "1",
      L: "0",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "206.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: " for 200 mm dia",
      item: "1",
      Nos: "1",
      L: "0",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "182.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: " for 150 mm dia",
      item: "1",
      Nos: "1",
      L: "0",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "166.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: " for 100 mm dia",
      item: "1",
      Nos: "1",
      L: "0",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "136.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "8",
      Description:
        "Lowering the CI Sluice valve in to the ready made trenches and keeping into the position etc, completefor",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 300mm dia S/V",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "778.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 250mm dia S/V",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "546.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 200mm dia S/V",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "385.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 150mm dia S/V",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "233.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 100mm dia S/V",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Each",
      Rate: "138.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "9",
      Description:
        "Jointing of CI D/F pipes and valves including cost of jointing materials such as nuts Bolts Rubber insuration etc, including all labour charges etc, complete                            ",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 300mm dia S/V",
      item: "2",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "644.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 250mm dia S/V",
      item: "2",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "610.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 200mm dia S/V",
      item: "2",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "432.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 150mm dia S/V",
      item: "2",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "399.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 100mm dia S/V",
      item: "2",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Nos",
      Rate: "265.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "10",
      Description:
        "Redoing  15 mm dia  damaged PPc connections including all materials etc. complete.",
      item: "1",
      Nos: "0",
      L: "4.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt",
      Rate: "201.00",
      unit: "1Rmt",
      Amount: "0.00"
    },
    {
      SlNo: "11",
      Description:
        "Redoing  100 mm dia  damaged sewer connections including all materials etc. complete.",
      item: "1",
      Nos: "0",
      L: "4.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt",
      Rate: "423.00",
      unit: "Rmt",
      Amount: "0.00"
    },
    {
      SlNo: "12",
      Description:
        "Supply delivery and fixing of RCC Precast Man Hole chamber of size 31\u0027\u0027x21\u0027\u0027 with FRC frame and Cover including CC bed complete etc, complete",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 300mm dia Sluice valves",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 250mm dia Sluice valves",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 200mm dia Sluice valves",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 150mm dia Sluice valves",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 100mm dia Sluice valves",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "7411.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "13",
      Description:
        "Barricading hoarding lighitng watching incl labor charges etc complete.",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 300mm dia",
      item: "1",
      Nos: "2",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 250mm dia",
      item: "1",
      Nos: "2",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 200mm dia",
      item: "1",
      Nos: "2",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 150mm dia",
      item: "1",
      Nos: "2",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 100mm dia",
      item: "1",
      Nos: "2",
      L: "0.00",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Rmt",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "Rmt",
      Rate: "128.69",
      unit: "Rmt",
      Amount: "0.00"
    },
    {
      SlNo: "14",
      Description:
        "Conveyence of pipe from Departmental Central stores to work site including cost and conveyence etc, complete.",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 300mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "49.39",
      D: "Kg/Rmt",
      Qty: "0.00",
      Qty_unit: "MT",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 250mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "39.20",
      D: "Kg/Rmt",
      Qty: "0.00",
      Qty_unit: "MT",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 200mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "30.02",
      D: "Kg/Rmt",
      Qty: "0.00",
      Qty_unit: "MT",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 150mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "22.84",
      D: "Kg/Rmt",
      Qty: "0.00",
      Qty_unit: "MT",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 100mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "15.37",
      D: "Kg/Rmt",
      Qty: "0.00",
      Qty_unit: "MT",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "MT",
      Rate: "1034.15",
      unit: "MT",
      Amount: "0.00"
    },
    {
      SlNo: "15",
      Description:
        "Making dummy arrangement with ci step collar and dummy plate nuts and bolts incl. insertion rubber sheet etc. complete.",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 150mmdia",
      item: "1",
      Nos: "",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "4485.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "for 100mmdia",
      item: "1",
      Nos: "",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "3066.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "16",
      Description:
        "Bailing out of water from pipe line trenches with oil engine driven and pump sets including hire charges, fuel charges and wages for driver and helpers etc., complete as directed by the departmental officers.",
      item: "",
      Nos: "",
      L: "Hp",
      B: "hrs/day",
      D: "days",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "1",
      Nos: "2",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "Hp/hr",
      Rate: "384.00",
      unit: "Hp/hr",
      Amount: "0.00"
    },
    {
      SlNo: "17",
      Description:
        "Manufacture, supply and delivery of Single Chamber DI Air Valve with Body and cover inDuctile Iron of grade GGG40/SG-400/15 or GGG-50/SG-500/7 or equivalent grade as perI.S.3896-part2-1985 and subsequent revisions.All internal parts such as float, shell etc., allcover bolts, of stainless steel, and Gaskets andseals of EPDM food grade quality Epoxypowder coating (EP-P) inside and outside colour blue. Drilled as per IS:1538. 100 mmdia (PN-10)",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "1",
      Nos: "",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "47888.00",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "18",
      Description:
        "Manufacture Supplying and erection of air valve guard cabins of size 1.80x1.80x1.80M made with 8 Nos vertical and 6 Nos horizontal MS angles and Top and also 4 Nos at Bottam of size 70x70x6 mm thcik etc complete with door and locking arrangements as directed by the departmental officers and painting both sides with anti corrossive paint two coats over one coat of primery coat including cost of all materials , fabrication ,welding , transportation to site, all taxes and duties,fixing in position duly embodying in CC(1:2:4) prop , and all other incidental and operational charges etc complete for finished item of work.(DATA ENCLOSED) ",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "1",
      Nos: "0",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "No.s",
      Rate: "24556.18",
      unit: "Each",
      Amount: "0.00"
    },
    {
      SlNo: "19",
      Description:
        "Supply ,delivery and filling of quarry dust (H B chips) for bedding to the pipeline trenches or wherever required including watering, tamping and ramming as directed by the dept.officers including cost and conveyance of quarry dust loading,unloading ,transportaion ,labour charges and all other incidental and operational charges etc, complete",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 300mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.30",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 250mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.30",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 200mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.30",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 150mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.30",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 100mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.30",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "923.00",
      unit: "Cum",
      Amount: "0.00"
    },
    {
      SlNo: "20",
      Description:
        "Laying of c.c.1:2:4 prop using 6mm-20mm guage hard granite material including labour charges for mixing ,laying etc.,complete.",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 300mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.00",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 250mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.00",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 200mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.00",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 150mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.00",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "for 100mm dia pipe line trenches",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "0.00",
      D: "0.00",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "5354.70",
      unit: "Cum",
      Amount: "0.00"
    },
    {
      SlNo: "21",
      Description:
        "Refilling the pipe line trenches with excavated soils other than sand including the cost of labour etc. complete.",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "Qty as per earth work excavation",
      item: "-",
      Nos: "-",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "Deduct pipe volume 300mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "x3.14x0.326x0.326/4",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "Deduct pipe volume 250mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "x3.14x0.274x0.274/4",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "Deduct pipe volume 200mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "x3.14x0.222x0.222/4",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "Deduct pipe volume 150mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "x3.14x0.170x0.170/4",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "Deduct pipe volume 100mm dia",
      item: "1",
      Nos: "1",
      L: "0.00",
      B: "x3.14x0.118x0.118/4",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "Deduct sluice valve chamber portion",
      item: "1",
      Nos: "0",
      L: "",
      B: "x3.14x(0.56+0.94)²/4",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "34.90",
      unit: "Cum",
      Amount: "0.00"
    },
    {
      SlNo: "22",
      Description:
        "Carting of surplus earth from worksite to a maximum lead of 3 kms. ",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "CC road quantity",
      item: "-",
      Nos: "-",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "Remaining Earth work quantity after refilling",
      item: "-",
      Nos: "-",
      L: "-",
      B: "-",
      D: "-",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "",
      unit: "",
      Amount: ""
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "0.00",
      Qty_unit: "Cum",
      Rate: "132.40",
      unit: "Cum",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "Total cost of Civil work  ",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "Rs./-",
      Amount: "0.00"
    },
    {
      SlNo: "",
      Description: "",
      item: "",
      Nos: "",
      L: "",
      B: "",
      D: "",
      Qty: "",
      Qty_unit: "",
      Rate: "",
      unit: "",
      Amount: ""
    }
  ];
  return row;
}
export default function createRowData() {
  //return [...Array(count).keys()].map(i => createFakeRow(i));
  return Rowdata();
}
